### ISSUE TITLE
Asset name in currency page should be capital letters

### ISSUE THREAD

**Issue by kezida** [entreprenrisk/FCO-Issues#40]
![image](https://user-images.githubusercontent.com/11725116/82322903-8d8bf700-99d7-11ea-959b-b59bdd910066.png)

Asset name in currency page should be capital letters

**Comment by Victor-Land** [comment]
Created BUG in Jira.
https://jira.hiendsys.ru/browse/FCO-484

**Comment by chahat** [comment]
fixed already
