### ISSUE TITLE
How search works??

### ISSUE THREAD

**Issue by chahat** [entreprenrisk/FCO-Issues#41]
Search shows asset on the Table view, but switching the tab the context is lost. All the tabs are searchable in itself. Searching on the main bar should lead me to Single Asset page somehow. So if you are searching on the table view then the asset name should be a link to the single asset page 

![2020-05-19_14h09_21](https://user-images.githubusercontent.com/2259404/82325566-bc0bd100-99db-11ea-9418-a463f59e0791.gif)

**Comment by Victor-Land** [comment]
Search functionality was implemented in a basic scenario, without sub-scenarios.  We have not got declared requirements for this feature. Time was not spent on additional implementations.
Created Improvement task: https://jira.hiendsys.ru/browse/FCO-485

**Comment by chahat** [comment]
The price (last 30 days) is the link to SAP .. however when on the searched on the main bar . by default hideBubleScore Zero is enabled when it goes to the table view because of which any asset that does not have a signal on that day is shown with a NA entry and hence it is not getting possible to reach the SAP for that asset. 

With 79b3c6f FCO-Frontend checkin by default the hideBubbleScoreZero setting is set to false. So now when you are comign from search bar to table view it should show the asset price and make it possible to navigate to the SAP 

However there is a fundamental flaw in this which I discuss in the readme of FCO-Frontened repo
