### ISSUE TITLE
Remove the search bar from cms part of website

### ISSUE THREAD

**Issue by chahat** [entreprenrisk/FCO-Issues#46]
Since you are not searchign inside news and articles.. this search bar should be disabled when on cms part of website . Disable it in the code. DO NOT REMOVE IT !!

![image](https://user-images.githubusercontent.com/2259404/82327031-1574ff80-99de-11ea-902c-e630caecda6d.png)

**Comment by Victor-Land** [comment]
We were not sure how it would be better to realize it on CMS. So we does not added search function to CMS. Time for it was not spent. 

Created an improvement task: https://jira.hiendsys.ru/browse/FCO-489

**Comment by chahat** [comment]
@hanyuei since you have other Wordpress bug (#62 ) , i give you this one aswell..

**Comment by hanyuei** [comment]
@chahat would you please check if this is what we want ?

![hide-search-from-cms](https://user-images.githubusercontent.com/6997095/95942723-834f1700-0e16-11eb-91f8-cb6e8fd3520f.png)
