### ISSUE TITLE
media dropdown shows only on wp website but not on main website

### ISSUE THREAD

**Issue by chahat** [entreprenrisk/FCO-Issues#47]
![2020-05-19_14h39_29](https://user-images.githubusercontent.com/2259404/82327400-a21fbd80-99de-11ea-8248-5a126ab49d34.gif)

**Comment by Victor-Land** [comment]
Created a bug: https://jira.hiendsys.ru/browse/FCO-494

**Comment by chahat** [comment]
Fixed
