### ISSUE TITLE
Crypto CCDF/PDF plot fix

### ISSUE THREAD

**Issue by kezida** [entreprenrisk/FCO-Issues#61]
- The y axis label should use the full name: Complementary Cumulative Distribution Function (CCDF) and  Probability Density Function (PDF).

- Please also add a x-axis label: Market Capitalization

- I am not able to switch days on the time bar or through the calendar, a bug?

- Remove the words in the box as indicated below
![image](https://user-images.githubusercontent.com/11725116/82428464-d81a7b80-9a8a-11ea-8dc0-7c573a4891f5.png)

**Comment by chahat** [comment]
Fixed with FCO-Frontend#5e3010a
