### ISSUE TITLE
lppls methodology plot adjustment

### ISSUE THREAD

**Issue by kezida** [entreprenrisk/FCO-Issues#62]
![image](https://user-images.githubusercontent.com/11725116/82429237-ddc49100-9a8b-11ea-8347-6310be6d7fa8.png)

As indicated before, please move the parameter and plot into a same row, with the parameter table on the left, and the plot on the right.

**Comment by chahat** [comment]
@hanyuei , you will find relevant code in Wordpress repository

**Comment by hanyuei** [comment]
This is the page after updated.

@kezida  would you please help check if this is what we want ?

- in small laptop screen 

![laptop](https://user-images.githubusercontent.com/6997095/95940728-ae833780-0e11-11eb-90eb-4b854fcdd198.gif)

- in larger screen

![larger-screen](https://user-images.githubusercontent.com/6997095/95940754-bfcc4400-0e11-11eb-9db6-e3fd074adf21.gif)
