### ISSUE TITLE
Bubble Score calculation wrong, LPPLS fits wrong, no parameter table

### ISSUE THREAD

**Issue by kezida** [entreprenrisk/FCO-Issues#73]
![image](https://user-images.githubusercontent.com/11725116/82914597-00651700-9f70-11ea-9d55-c1937cc183db.png)

How do you calculate Bubble Score? It should only have a range of -100% to 100%. Now it shows a value larger than 100%. The formula is "signal_mean" x "signal" x sign("BubbleSize"). "signal_mean", "signal", and "BubbleSize" are three columns in the database. "signal_mean" ranges in 0 to 1, "signal" is a TRUE or FALSE value, and "BubbleSize" is a value larger than 0.

We also checked that the LPPLS fit plots are exactly the same as our records. Can you give the explicit formula plotting the fits?

Where is the parameter table as agreed on the design below the chart?

**Comment by chahat** [comment]
The formula was fixed in the backend when refactoring all the wrong sql scripts .. 
Fixed with c1c32ef 1) Pids(1,2) are interchanged for normal assets
