### ISSUE TITLE
The button of "Download CSV" at the Individual Stock page should be moved to right

### ISSUE THREAD

**Issue by kezida** [entreprenrisk/FCO-Issues#80]
![image](https://user-images.githubusercontent.com/11725116/95164763-2b445f00-07dd-11eb-8080-ed8379aa68ac.png)

Due to the button of "Download CSV", one can't click on the price series to show the LPPLS fits.

**Comment by chahat** [comment]
Fixed with FCO-Frontend-HES # 4205e11
